version: "3.9"

services:
  db:
    image: postgres:16
    container_name: himalayan_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Butwal8
      POSTGRES_DB: himalayan_taste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:Butwal8@db:5432/himalayan_taste
    container_name: himalayan_web
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Butwal8@db:5432/himalayan_taste
    command: sh -c "npx prisma generate && npm run start"

volumes:
  postgres_data:
